"""empty message

Revision ID: 1de4b79c7fcc
Revises: 
Create Date: 2018-12-07 12:15:56.054078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de4b79c7fcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wfnj_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wxname', sa.String(length=50), nullable=False),
    sa.Column('truename', sa.String(length=50), nullable=True),
    sa.Column('tel', sa.String(length=11), nullable=False),
    sa.Column('portrait', sa.String(length=200), nullable=True),
    sa.Column('datatime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tel')
    )
    op.create_table('wfnj_userlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['wfnj_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wfnj_userlog_addtime'), 'wfnj_userlog', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wfnj_userlog_addtime'), table_name='wfnj_userlog')
    op.drop_table('wfnj_userlog')
    op.drop_table('wfnj_user')
    # ### end Alembic commands ###
