"""empty message

Revision ID: 7de55628ff6c
Revises: a49f9c473366
Create Date: 2018-12-19 10:10:11.153415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de55628ff6c'
down_revision = 'a49f9c473366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'wfnj_userlog', 'wfnj_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wfnj_userlog', type_='foreignkey')
    # ### end Alembic commands ###
