"""empty message

Revision ID: a12c76533511
Revises: 
Create Date: 2018-12-07 09:28:41.535137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12c76533511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wfnj_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wxname', sa.String(length=50), nullable=False),
    sa.Column('truename', sa.String(length=50), nullable=True),
    sa.Column('tel', sa.String(length=11), nullable=False),
    sa.Column('portrait', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wfnj_users')
    # ### end Alembic commands ###
