"""empty message

Revision ID: a49f9c473366
Revises: 80254624323d
Create Date: 2018-12-19 09:30:53.990593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a49f9c473366'
down_revision = '80254624323d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wfnj_user', sa.Column('hash_password', sa.String(length=50), nullable=True))
    op.drop_column('wfnj_user', 'password')
    op.create_foreign_key(None, 'wfnj_userlog', 'wfnj_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wfnj_userlog', type_='foreignkey')
    op.add_column('wfnj_user', sa.Column('password', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('wfnj_user', 'hash_password')
    # ### end Alembic commands ###
